# Generated by Django 4.2.3 on 2023-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='humanRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='label',
            field=models.TextField(null=True, blank=True,default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='nonGG',
            field=models.BooleanField(default=False),
        ),
    ]
