# Generated by Django 4.2.3 on 2023-09-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_humanrequired_message_label_message_nongg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='label',
            field=models.TextField(default='Basic'),
        ),
    ]
