# Generated by Django 4.2.3 on 2023-09-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='label',
            field=models.TextField(default=None),
        ),
    ]
